# Generated by Django 5.1.7 on 2025-03-30 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')])),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=20)),
                ('email1', models.EmailField(max_length=254, verbose_name='Email Principal')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Secundario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atraso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrasos', to='registro.estudiante')),
            ],
            options={
                'verbose_name': 'Atraso',
                'verbose_name_plural': 'Atrasos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
