# Generated by Django 5.1.7 on 2025-04-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['curso', 'nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(choices=[('Pre-Kínder A', 'Pre-Kínder A'), ('Pre-Kínder B', 'Pre-Kínder B'), ('Kínder A', 'Kínder A'), ('Kínder B', 'Kínder B'), ('1° Básico A', '1° Básico A'), ('1° Básico B', '1° Básico B'), ('2° Básico A', '2° Básico A'), ('2° Básico B', '2° Básico B'), ('3° Básico A', '3° Básico A'), ('3° Básico B', '3° Básico B'), ('4° Básico A', '4° Básico A'), ('4° Básico B', '4° Básico B'), ('5° Básico A', '5° Básico A'), ('5° Básico B', '5° Básico B'), ('6° Básico A', '6° Básico A'), ('6° Básico B', '6° Básico B'), ('7° Básico A', '7° Básico A'), ('7° Básico B', '7° Básico B'), ('8° Básico A', '8° Básico A'), ('8° Básico B', '8° Básico B'), ('1° Medio A', '1° Medio A'), ('1° Medio B', '1° Medio B'), ('2° Medio A', '2° Medio A'), ('2° Medio B', '2° Medio B'), ('3° Medio A', '3° Medio A'), ('3° Medio B', '3° Medio B'), ('4° Medio A', '4° Medio A'), ('4° Medio B', '4° Medio B')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email_principal',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True),
        ),
    ]
