# Generated by Django 5.1.7 on 2025-03-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atraso',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
