# Generated by Django 5.1.7 on 2025-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_atraso_fecha_alter_atraso_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraso',
            name='curso',
            field=models.CharField(choices=[('Pre-Kínder A', 'Pre-Kínder A'), ('Kínder A', 'Kínder A'), ('1° Básico A', '1° Básico A'), ('2° Básico A', '2° Básico A'), ('3° Básico A', '3° Básico A'), ('4° Básico A', '4° Básico A'), ('5° Básico A', '5° Básico A'), ('6° Básico A', '6° Básico A'), ('7° Básico A', '7° Básico A'), ('8° Básico A', '8° Básico A'), ('1° Medio A', '1° Medio A'), ('2° Medio A', '2° Medio A'), ('3° Medio A', '3° Medio A'), ('4° Medio A', '4° Medio A'), ('Pre-Kínder B', 'Pre-Kínder B'), ('Kínder B', 'Kínder B'), ('1° Básico B', '1° Básico B'), ('2° Básico B', '2° Básico B'), ('3° Básico B', '3° Básico B'), ('4° Básico B', '4° Básico B'), ('5° Básico B', '5° Básico B'), ('6° Básico B', '6° Básico B'), ('7° Básico B', '7° Básico B'), ('8° Básico B', '8° Básico B'), ('1° Medio B', '1° Medio B'), ('2° Medio B', '2° Medio B'), ('3° Medio B', '3° Medio B'), ('4° Medio B', '4° Medio B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(choices=[('Pre-Kínder A', 'Pre-Kínder A'), ('Kínder A', 'Kínder A'), ('1° Básico A', '1° Básico A'), ('2° Básico A', '2° Básico A'), ('3° Básico A', '3° Básico A'), ('4° Básico A', '4° Básico A'), ('5° Básico A', '5° Básico A'), ('6° Básico A', '6° Básico A'), ('7° Básico A', '7° Básico A'), ('8° Básico A', '8° Básico A'), ('1° Medio A', '1° Medio A'), ('2° Medio A', '2° Medio A'), ('3° Medio A', '3° Medio A'), ('4° Medio A', '4° Medio A'), ('Pre-Kínder B', 'Pre-Kínder B'), ('Kínder B', 'Kínder B'), ('1° Básico B', '1° Básico B'), ('2° Básico B', '2° Básico B'), ('3° Básico B', '3° Básico B'), ('4° Básico B', '4° Básico B'), ('5° Básico B', '5° Básico B'), ('6° Básico B', '6° Básico B'), ('7° Básico B', '7° Básico B'), ('8° Básico B', '8° Básico B'), ('1° Medio B', '1° Medio B'), ('2° Medio B', '2° Medio B'), ('3° Medio B', '3° Medio B'), ('4° Medio B', '4° Medio B')], max_length=20),
        ),
    ]
