# Generated by Django 5.1.7 on 2025-04-01 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_atraso_curso_alter_estudiante_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(help_text='Formato: XXXXXXXXX-X o XXXXXXXXX-K (sin puntos ni guion)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato XXXXXXXXX-X o XXXXXXXXX-K', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
    ]
